version: '3.8'

services:
  todo:
    build: ./todo
    container_name: todo_c
    ports:
      - '3000:3000'
    volumes:
      - ./todo:/app
      - ./app/node_modules:/app/node_modules
    stdin_open: true
    tty: true
